
------------ NDM WISE MTD SALES
SELECT 
[NDM].[NDMNAME] 
,SUM([OESalesDetails].[EXTINVMISC]) AS SALES
FROM [OESalesDetails]
LEFT JOIN [NDM] ON [OESalesDetails].AUDTORG = [NDM].[BRANCH]
Where 
([TRANSDATE] BETWEEN 
convert(varchar(8),DATEADD(mm, DATEDIFF(mm, 0, GETDATE()), 0),112) --- FIRST DAY OF CURRENT MONTH
AND 
convert(varchar(8),DATEADD(D,-1,GETDATE()),112)) --- YESTERDAY
GROUP BY [NDM].[NDMNAME]
ORDER BY [NDM].[NDMNAME]
